# Generated by Django 4.1.7 on 2024-07-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=256)),
                ("topic_id", models.CharField(max_length=256)),
                ("chat_id", models.IntegerField()),
                ("question", models.TextField()),
                ("response", models.TextField()),
            ],
            options={
                "db_table": "chat_history",
                "managed": False,
            },
        ),
    ]
